### ISSUE TITLE
Default password?

### ISSUE THREAD

**Issue by killmasta93** [gurucomputing/meshcentral-docker#4]
Hi
I was wondering what is the default password?
Im trying to configure so it runs on another port would it work if i put a reverse proxy in front of it? 

Thank you

**Comment by routerino** [comment]
Hi killmasta,

Sorry about the delay in reply, just realized I wasn't getting notified anymore.

There is no default password, the first user you create is an administrator.

**Comment by killmasta93** [comment]
thank you
