### ISSUE TITLE
Is it possible to change the user/group under which it will run ?

### ISSUE THREAD

**Issue by palijn** [gurucomputing/meshcentral-docker#7]
Hello,
is it possible to change the user/group ID under which it will run? 
I read that it will run as the user node(1000,1000) but this is undesirable in my Docker environment. I would like to use a _meshcentral(1047, 65535) user. Can I define it in the docker-compose.yml file , or as environment variables ?
Thanks for your support !

**Comment by routerino** [comment]
Yes, you can define a custom user in the docker compose file. You will need to make sure your bind mounts reflect the changed permissions.
